/* eslint-disable import/prefer-default-export */

// Default constants
export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';
export const FETCH_CONTENT_START = 'FETCH_CONTENT_START';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_ERROR = 'FETCH_CONTENT_ERROR';

// Model states
export const STATUS_ACTIVE = 'active';
export const STATUS_INACTIVE = 'inactive';

// Redux actions
export const GET_SITE = 'GET_SITE';
export const GET_SITES = 'GET_SITES';
export const CREATE_SITE = 'CREATE_SITE';
export const UPDATE_SITE = 'UPDATE_SITE';
export const DELETE_SITE = 'DELETE_SITE';

export const GET_ZONE = 'GET_ZONE';
export const GET_ZONES = 'GET_ZONES';
export const CREATE_ZONE = 'CREATE_ZONE';
export const UPDATE_ZONE = 'UPDATE_ZONE';
export const DELETE_ZONE = 'DELETE_ZONE';
export const GET_ZONES_FILTERS = 'GET_ZONES_FILTERS';
export const SET_ZONES_FILTERS = 'SET_ZONES_FILTERS';

export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS_FILTERS = 'GET_USERS_FILTERS';
export const SET_USERS_FILTERS = 'SET_USERS_FILTERS';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';

export const GET_ROLE = 'GET_ROLE';
export const GET_ROLES = 'GET_ROLES';
export const CREATE_ROLE = 'CREATE_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const GET_ROLES_FILTERS = 'GET_ROLES_FILTERS';
export const SET_ROLES_FILTERS = 'SET_ROLES_FILTERS';

export const GET_ADVERTISER = 'GET_ADVERTISER';
export const GET_ADVERTISERS = 'GET_ADVERTISERS';
export const CREATE_ADVERTISER = 'CREATE_ADVERTISER';
export const UPDATE_ADVERTISER = 'UPDATE_ADVERTISER';
export const DELETE_ADVERTISER = 'DELETE_ADVERTISER';

export const GET_CAMPAIGN = 'GET_CAMPAIGN';
export const GET_CAMPAIGNS = 'GET_CAMPAIGNS';
export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const GET_CAMPAIGNS_FILTERS = 'GET_CAMPAIGNS_FILTERS';
export const SET_CAMPAIGNS_FILTERS = 'SET_CAMPAIGNS_FILTERS';

export const GET_PLACEMENT = 'GET_PLACEMENT';
export const GET_PLACEMENTS = 'GET_PLACEMENTS';
export const CREATE_PLACEMENT = 'CREATE_PLACEMENT';
export const UPDATE_PLACEMENT = 'UPDATE_PLACEMENT';
export const DELETE_PLACEMENT = 'DELETE_PLACEMENT';
export const GET_PLACEMENTS_FILTERS = 'GET_PLACEMENTS_FILTERS';
export const SET_PLACEMENTS_FILTERS = 'SET_PLACEMENTS_FILTERS';

export const GET_BANNER = 'GET_BANNER';
export const GET_BANNERS = 'GET_BANNERS';
export const CREATE_BANNER = 'CREATE_BANNER';
export const UPDATE_BANNER = 'UPDATE_BANNER';
export const DELETE_BANNER = 'DELETE_BANNER';
export const SET_BANNERS_FILTERS = 'SET_BANNERS_FILTERS';
export const GET_BANNERS_FILTERS = 'GET_BANNERS_FILTERS';

export const CREATE_PLACEMENT_BANNER_ZONE = 'CREATE_PLACEMENT_BANNER_ZONE';
export const REMOVE_PLACEMENT_BANNER_ZONE = 'REMOVE_PLACEMENT_BANNER_ZONE';
